module.exports = {
  source: ['sd-input/src/sd-input.json'],
  fileHeader: {
    autoGeneratedFileHeader: () => {
      return [`Do not edit directly, this file was auto-generated`];
    },
  },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'tokens/',
      prefix: 'ch3plus',
      files: [
        {
          destination: 'variables.css',
          format: 'css/variables',
          options: {
            fileHeader: 'autoGeneratedFileHeader',
          },
        },
      ],
    },
    scss: {
      transformGroup: 'scss',
      buildPath: 'tokens/scss/',
      prefix: 'ch3plus',
      files: [{
        destination:'_variables.scss',
        format: 'scss/variables'
      }]
    },
    android: {
      transformGroup: 'android',
      buildPath: 'tokens/android/',
      prefix: 'ch3plus',
      files: [
        {
          destination: 'font_dimens.xml',
          format: 'android/fontDimens',
        },
        {
          destination: 'colors.xml',
          format: 'android/colors'
        }
      ],
    },
  },
};
